org: sapradi
app: poke-aws
service: poke-aws

provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:654654553644:table/pokeTable

functions:
  createPokemon:
    handler: src/addPokemon.addPokemon
    events:
      - httpApi:
          path: /pokemons
          method: post
            
  getPokemons:
    handler: src/getPokemons.getPokemons
    events:
      - httpApi:
          path: /pokemons
          method: get

  getPokemon:
    handler: src/getPokemon.getPokemon
    events:
      - httpApi:
          path: /pokemons/{id}
          method: get

  searchPokemons:
    handler: src/searchPokemons.searchPokemons
    events:
      - httpApi:
          path: /pokemons/search
          method: get

resources:
  Resources:
    pokeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pokeTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH